---
  :concurrency: 5
  staging:
    :concurrency: 10
  production:
    :concurrency: 20
  :queues:
    - default
    - [reading, 5]
    - [writing, 3]
    - [cron_task, 2]
  :schedule:
    get_news_from_external_resources:
      dynamic: true
      cron: '30 23 * * SUN'
      class: NewsWorkers::GetExternalNewsWorker
      queue: cron_task
      description: 'This worker retrieves all news from external resources'
